//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        public int BookID { get; set; }
        public int CategoryID { get; set; }
        public string BookName { get; set; }
        public string Author { get; set; }
        public string Describe { get; set; }
        public Nullable<System.DateTime> Publish { get; set; }
        public string Publisher { get; set; }
        public string BookImage { get; set; }
        public string BookStatus { get; set; }
    
        public virtual BORROW BORROW { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
    }
}
