//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        public int BorrowID { get; set; }
        public string StudentID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<System.DateTime> TakenDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
