//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        public int CategoryID { get; set; }
        public int BookID { get; set; }
        public string CategoryName { get; set; }
        public string Status { get; set; }
    
        public virtual BOOK BOOK { get; set; }
    }
}
