//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietMuonTra
    {
        public int isbn { get; set; }
        public int ma_phieumuontra { get; set; }
        public string ma_cuonsach { get; set; }
        public string ma_sinhvien { get; set; }
        public Nullable<System.DateTime> ngayGio_tra { get; set; }
        public Nullable<int> soluong { get; set; }
        public string ghichu { get; set; }
    
        public virtual CuonSach CuonSach { get; set; }
        public virtual MuonTra MuonTra { get; set; }
    }
}
