//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLTVEntities : DbContext
    {
        public QLTVEntities()
            : base("name=QLTVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BOOK> BOOKs { get; set; }
        public DbSet<BOOKRETURN> BOOKRETURNs { get; set; }
        public DbSet<BORROW> BORROWs { get; set; }
        public DbSet<CATEGORY> CATEGORies { get; set; }
        public DbSet<FINE> FINEs { get; set; }
        public DbSet<LIBRARYCARD> LIBRARYCARDs { get; set; }
        public DbSet<STUDENT> STUDENTs { get; set; }
        public DbSet<USER> USERS { get; set; }
    }
}
