//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuonSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuonSach()
        {
            this.ChiTietMuonTras = new HashSet<ChiTietMuonTra>();
        }
    
        public int isbn { get; set; }
        public string ma_cuonsach { get; set; }
        public string ten_cuonsach { get; set; }
        public string tacgia { get; set; }
        public Nullable<System.DateTime> namxuatban { get; set; }
        public string nhaxuatban { get; set; }
        public string ma_loaisach { get; set; }
        public string TinhTrang { get; set; }
        public string Mota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietMuonTra> ChiTietMuonTras { get; set; }
        public virtual DauSach DauSach { get; set; }
        public virtual LoaiSach LoaiSach { get; set; }
    }
}
