//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muon
    {
        public int isbn { get; set; }
        public string ma_cuonsach { get; set; }
        public string ma_sinhvien { get; set; }
        public System.DateTime ngayGio_muon { get; set; }
        public System.DateTime ngay_hethan { get; set; }
    
        public virtual CuonSach CuonSach { get; set; }
        public virtual TheThuVien TheThuVien { get; set; }
    }
}
