//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuonTra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MuonTra()
        {
            this.ChiTietMuonTras = new HashSet<ChiTietMuonTra>();
        }
    
        public int ma_phieumuontra { get; set; }
        public string ma_sinhvien { get; set; }
        public int MaNV { get; set; }
        public System.DateTime ngayGio_muon { get; set; }
        public Nullable<System.DateTime> ngay_hethan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietMuonTra> ChiTietMuonTras { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhieuPhat PhieuPhat { get; set; }
        public virtual TheThuVien TheThuVien { get; set; }
    }
}
