//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_Thu_Vien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Book = new HashSet<Book>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string Stat { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Book> Book { get; set; }
    }
}
