//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_Thu_Vien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public int FineID { get; set; }
        public Nullable<int> BorowID { get; set; }
        public Nullable<int> ReturnID { get; set; }
        public string FineAmount { get; set; }
    
        public virtual BookReturn BookReturn { get; set; }
    }
}
