//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_Thu_Vien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryCard
    {
        public LibraryCard()
        {
            this.Student = new HashSet<Student>();
        }
    
        public int CardID { get; set; }
        public string StudentName { get; set; }
        public Nullable<System.DateTime> DateExpires { get; set; }
        public string Issue { get; set; }
    
        public virtual ICollection<Student> Student { get; set; }
    }
}
