//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_Thu_Vien.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CNPM_QLTVEntities : DbContext
    {
        public CNPM_QLTVEntities()
            : base("name=CNPM_QLTVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Book> Book { get; set; }
        public DbSet<BookReturn> BookReturn { get; set; }
        public DbSet<Borrow> Borrow { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<Fine> Fine { get; set; }
        public DbSet<LibraryCard> LibraryCard { get; set; }
        public DbSet<Student> Student { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
