//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_Thu_Vien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Borrow = new HashSet<Borrow>();
        }
    
        public string StudentID { get; set; }
        public Nullable<int> CardID { get; set; }
        public string StudentName { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Addr { get; set; }
    
        public virtual ICollection<Borrow> Borrow { get; set; }
        public virtual LibraryCard LibraryCard { get; set; }
    }
}
